apiVersion: "v1"
kind: "List"
items:
-
  apiVersion: "v1"
  kind: "Template"
  metadata:
    name: fluentd-roles-template
    labels:
      logging-infra: fluentd
    annotations:
      description: "Template for creating the deployer account and roles needed for the aggregated logging deployer. Create as cluster-admin."
      tags: "infrastructure"
  objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aggregated-logging-fluentd
      labels:
        logging-infra: fluentd
